<?php

return [
    'disk' => env('MEDIA_DISK', 'media_local'),
    'bucket' => env(
        'MEDIA_STORAGE_BUCKET',
        env('MEDIA_AWS_BUCKET', env('AWS_BUCKET', 'local-media'))
    ),
    'region' => env('MEDIA_AWS_DEFAULT_REGION', env('AWS_DEFAULT_REGION')),
    'storage_class' => env('MEDIA_AWS_STORAGE_CLASS'),
    'signed_url_ttl_minutes' => (int) env('MEDIA_SIGNED_URL_TTL_MINUTES', 10),
    'max_upload_kilobytes' => (int) env('MEDIA_MAX_UPLOAD_KILOBYTES', 102400),
    'ffprobe_binary' => env('MEDIA_FFPROBE_BINARY', 'ffprobe'),
    'ffprobe_timeout_seconds' => (int) env('MEDIA_FFPROBE_TIMEOUT_SECONDS', 15),
    'processing' => [
        'fake' => [
            'virus_infected' => (bool) env('MEDIA_FAKE_VIRUS_INFECTED', false),
        ],
        'providers' => [
            'virus_scan' => env('MEDIA_VIRUS_SCAN_PROVIDER', 'unconfigured'),
            'ocr' => env('MEDIA_OCR_PROVIDER', 'unconfigured'),
            'speech_to_text' => env('MEDIA_SPEECH_TO_TEXT_PROVIDER', 'unconfigured'),
            'caption' => env('MEDIA_CAPTION_PROVIDER', 'unconfigured'),
            'thumbnail' => env('MEDIA_THUMBNAIL_PROVIDER', 'unconfigured'),
            'transcode' => env('MEDIA_TRANSCODE_PROVIDER', 'unconfigured'),
        ],
        'versions' => [
            'virus_scan' => env('MEDIA_VIRUS_SCAN_VERSION', 'unconfigured-v1'),
            'ocr' => env('MEDIA_OCR_VERSION', 'unconfigured-v1'),
            'speech_to_text' => env('MEDIA_SPEECH_TO_TEXT_VERSION', 'unconfigured-v1'),
            'caption' => env('MEDIA_CAPTION_VERSION', 'unconfigured-v1'),
            'thumbnail' => env('MEDIA_THUMBNAIL_VERSION', 'unconfigured-v1'),
            'transcode' => env('MEDIA_TRANSCODE_VERSION', 'unconfigured-v1'),
        ],
    ],
    'file_types' => [
        'image',
        'video',
        'audio',
        'document',
        'subtitle',
        'transcript',
        'archive',
        'other',
    ],
    'visibility' => [
        'private',
        'organization',
        'public',
    ],
    'owner_types' => [
        'course_template',
        'course_template_version',
        'course_category',
        'course_product',
        'course_activity',
        'course_version_activity',
        'course_cohort',
        'assessment_question',
        'assessment_answer',
        'liveclass_recording',
        'certificate',
        'avatar',
        'ai_knowledge',
        'marketing',
    ],
    'usage_types' => [
        'intro_image',
        'intro_video',
        'intro_document',
        'cover_image',
        'thumbnail',
        'banner_image',
        'video',
        'audio',
        'document',
        'attachment',
        'recording',
        'certificate_pdf',
        'avatar_image',
        'source_material',
    ],
];
