<?php

return [
    'disk' => env('MEDIA_DISK', 'media_local'),
    'bucket' => env(
        'MEDIA_STORAGE_BUCKET',
        env('MEDIA_AWS_BUCKET', env('AWS_BUCKET', 'local-media'))
    ),
    'region' => env('MEDIA_AWS_DEFAULT_REGION', env('AWS_DEFAULT_REGION')),
    'storage_class' => env('MEDIA_AWS_STORAGE_CLASS'),
    'signed_url_ttl_minutes' => (int) env('MEDIA_SIGNED_URL_TTL_MINUTES', 10),
    'max_upload_kilobytes' => (int) env('MEDIA_MAX_UPLOAD_KILOBYTES', 102400),
    'ffprobe_binary' => env('MEDIA_FFPROBE_BINARY', 'ffprobe'),
    'ffprobe_timeout_seconds' => (int) env('MEDIA_FFPROBE_TIMEOUT_SECONDS', 15),
    'processing' => [
        'fake' => [
            'virus_infected' => (bool) env('MEDIA_FAKE_VIRUS_INFECTED', false),
        ],
        'local_document' => [
            'pdftotext_binary' => env('MEDIA_PDFTOTEXT_BINARY', 'pdftotext'),
            'pdftoppm_binary' => env('MEDIA_PDFTOPPM_BINARY', 'pdftoppm'),
            'pdfinfo_binary' => env('MEDIA_PDFINFO_BINARY', 'pdfinfo'),
            'tesseract_binary' => env('MEDIA_TESSERACT_BINARY', 'tesseract'),
            'soffice_binary' => env('MEDIA_SOFFICE_BINARY', 'soffice'),
            'command_timeout_seconds' => (int) env('MEDIA_DOCUMENT_COMMAND_TIMEOUT_SECONDS', 300),
            'office_timeout_seconds' => (int) env('MEDIA_OFFICE_TIMEOUT_SECONDS', 900),
            'max_processing_seconds' => (int) env('MEDIA_DOCUMENT_MAX_PROCESSING_SECONDS', 3300),
            'max_pages' => (int) env('MEDIA_DOCUMENT_MAX_PAGES', 100),
            'max_docx_xml_bytes' => (int) env('MEDIA_DOCX_MAX_XML_BYTES', 8000000),
            'ocr_dpi' => (int) env('MEDIA_OCR_DPI', 200),
            'max_extracted_characters' => (int) env('MEDIA_MAX_EXTRACTED_CHARACTERS', 500000),
        ],
        'structured_extraction' => [
            'max_pages' => (int) env('MEDIA_STRUCTURED_MAX_PAGES', 100),
            'max_extracted_characters' => (int) env('MEDIA_STRUCTURED_MAX_EXTRACTED_CHARACTERS', 500000),
            'max_regions_per_page' => (int) env('MEDIA_STRUCTURED_MAX_REGIONS_PER_PAGE', 100),
            'max_regions_per_document' => (int) env('MEDIA_STRUCTURED_MAX_REGIONS_PER_DOCUMENT', 5000),
            'max_table_cells_per_document' => (int) env('MEDIA_STRUCTURED_MAX_TABLE_CELLS_PER_DOCUMENT', 200000),
            'max_processing_seconds' => (int) env('MEDIA_STRUCTURED_MAX_PROCESSING_SECONDS', 3300),
            'command_timeout_seconds' => (int) env('MEDIA_STRUCTURED_COMMAND_TIMEOUT_SECONDS', 900),
        ],
        'docling' => [
            'python_binary' => env('MEDIA_DOCLING_PYTHON_BINARY', base_path('runtime/docling/.venv/bin/python')),
            'script' => env('MEDIA_DOCLING_SCRIPT', base_path('runtime/docling/extract.py')),
            'artifacts_path' => env('MEDIA_DOCLING_ARTIFACTS_PATH', base_path('runtime/docling/models')),
            'timeout_seconds' => (int) env('MEDIA_DOCLING_TIMEOUT_SECONDS', 3300),
            'max_output_bytes' => (int) env('MEDIA_DOCLING_MAX_OUTPUT_BYTES', 67108864),
        ],
        'limits' => [
            'max_extracted_characters' => (int) env('MEDIA_MAX_EXTRACTED_CHARACTERS', 500000),
        ],
        'providers' => [
            'virus_scan' => env('MEDIA_VIRUS_SCAN_PROVIDER', 'unconfigured'),
            'ocr' => env('MEDIA_OCR_PROVIDER', 'unconfigured'),
            'speech_to_text' => env('MEDIA_SPEECH_TO_TEXT_PROVIDER', 'unconfigured'),
            'caption' => env('MEDIA_CAPTION_PROVIDER', 'unconfigured'),
            'thumbnail' => env('MEDIA_THUMBNAIL_PROVIDER', 'unconfigured'),
            'transcode' => env('MEDIA_TRANSCODE_PROVIDER', 'unconfigured'),
            'structured_extraction' => env('MEDIA_STRUCTURED_EXTRACTION_PROVIDER', 'unconfigured'),
        ],
        'versions' => [
            'virus_scan' => env('MEDIA_VIRUS_SCAN_VERSION', 'unconfigured-v1'),
            'ocr' => env('MEDIA_OCR_VERSION', 'unconfigured-v1'),
            'speech_to_text' => env('MEDIA_SPEECH_TO_TEXT_VERSION', 'unconfigured-v1'),
            'caption' => env('MEDIA_CAPTION_VERSION', 'unconfigured-v1'),
            'thumbnail' => env('MEDIA_THUMBNAIL_VERSION', 'unconfigured-v1'),
            'transcode' => env('MEDIA_TRANSCODE_VERSION', 'unconfigured-v1'),
            'structured_extraction' => env('MEDIA_STRUCTURED_EXTRACTION_VERSION', 'unconfigured-v1'),
        ],
    ],
    'file_types' => [
        'image',
        'video',
        'audio',
        'document',
        'subtitle',
        'transcript',
        'archive',
        'other',
    ],
    'visibility' => [
        'private',
        'organization',
        'public',
    ],
    'owner_types' => [
        'course_template',
        'course_template_version',
        'course_category',
        'course_product',
        'course_activity',
        'course_version_activity',
        'course_cohort',
        'assessment_question',
        'assessment_answer',
        'liveclass_recording',
        'certificate',
        'avatar',
        'ai_knowledge',
        'marketing',
    ],
    'usage_types' => [
        'intro_image',
        'intro_video',
        'intro_document',
        'cover_image',
        'thumbnail',
        'banner_image',
        'video',
        'audio',
        'document',
        'attachment',
        'recording',
        'certificate_pdf',
        'avatar_image',
        'source_material',
    ],
];
